version: '3.8'
services:
  spark-master:
    image: bitnami/spark:4.0.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    volumes:
      - ./data:/app/data
  spark-worker:
    image: bitnami/spark:4.0.0
    deploy:
      replicas: 3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - ./data:/app/data
  pyspark-client:
    build: .
    container_name: pyspark-client
    depends_on:
      - spark-master
    ports:
      - "6000:6000"
    networks:
      - spark-net
    volumes:
      - ./data/parquet:/app/data/parquet
networks:
  spark-net:
